### ISSUE TITLE
User Manual

### ISSUE THREAD

**Issue by Minnielam** [brandherd/PyParadise#4]
Hi @brandherd,

I read the user manual and the latest version code again, since Guilherme found the name of 'Paradise' no longer existed in the latest version. Indeed, the package name has been changed. so, I guess Chapter 10 in the user manual requires to update slightly, which will be,

'from PyParadise import * '

Thanks a lot for updating the code.

Best Regards,
Man I

**Comment by brandherd** [comment]
This issue refers the old Manual where a code example is given. In the new version this chapter does not exist anymore. I have removed the old manual from the repository to avoid further confusion.
