### ISSUE TITLE
Missing lines.fit file the examples dir

### ISSUE THREAD

**Issue by stevennrr** [brandherd/PyParadise#7]
Hi, PyParadise seems to be up and running for me - im just missing the lines.fit script. Otherwise, its all good! Would you be able to update the git and add in the lines.fit file?

**Comment by gscouto** [comment]
Hi Steven,
The lines.fit file is just a text file giving the wavelength range you want each emission line to be fitted within, and you can edit yourself. See an example attached (you should rename the file to lines.fit; github doesnt allow to attach a .fit file). 
Hope this helps,
Guilherme
[lines_fit.txt](https://github.com/brandherd/PyParadise/files/12856032/lines_fit.txt)

**Comment by stevennrr** [comment]
Works perfectly! Thank you!
